export const commentConnuNRU = [
    { id: 1, libelle: 'Internet' },
    { id: 2, libelle: 'Logiciel' },
    { id: 3, libelle: 'Confrères' },
    { id: 4, libelle: 'Contact Commercial' },
    { id: 5, libelle: 'Annuaire' },
    { id: 6, libelle: 'Réseaux Sociaux' },
    { id: 7, libelle: 'Emailing' },
    { id: 8, libelle: 'Bouche à oreille' },
    { id: 9, libelle: 'Au cours d\'un événement' }
    // { id: 10, libelle: 'Formation RTC avec Inafon' },
    // { id: 11, libelle: 'RAID des notaires 2023' },
    // { id: 12, libelle: 'AG Val de Loire 07/11/2023' },
    // { id: 13, libelle: 'Congrès des Notaires 2023' },
    // { id: 14, libelle: 'Rentrée Notariale Hautes Alpes 21/09' },
    // { id: 15, libelle: 'Cyclonot 2023' },
    // { id: 16, libelle: 'Juris Cup 2023' },
    // { id: 17, libelle: 'Soirée Jeune notaire Lille juin 2023' },
    // { id: 18, libelle: 'Challen JN 2023' },
    // { id: 19, libelle: 'Syndicat National des Notaires 2023' },
    // { id: 20, libelle: 'Assemblée Générale de la Drôme' },
    // { id: 21, libelle: 'Université de la Négociation Notariale Deauville 2023' },
    // { id: 22, libelle: 'Notalab 2023' },
    // { id: 23, libelle: 'Université Famille et Immobilier Cannes' },
]
