export const formesJuridiques = [
    { code: '0000', designation: 'Organisme de placement collectif en valeurs mobilières sans personnalité morale' },
    { code: '1000', designation: 'Entrepreneur individuel' },
    { code: '2110', designation: 'Indivision entre personnes physiques' },
    { code: '2120', designation: 'Indivision avec personne morale' },
    { code: '2210', designation: 'Société créée de fait entre personnes physiques' },
    { code: '2220', designation: 'Société créée de fait avec personne morale' },
    { code: '2310', designation: 'Société en participation entre personnes physiques' },
    { code: '2320', designation: 'Société en participation avec personne morale' },
    { code: '2385', designation: 'Société en participation de professions libérales' },
    { code: '2400', designation: 'Fiducie' },
    { code: '2700', designation: 'Paroisse hors zone concordataire' },
    { code: '2800', designation: 'Assujetti unique à la TVA' },
    { code: '2900', designation: 'Autre groupement de droit privé non doté de la personnalité morale' },
    { code: '3110', designation: 'Représentation ou agence commerciale d\'état ou organisme public étranger immatriculé au RCS' },
    { code: '3120', designation: 'Société commerciale étrangère immatriculée au RCS' },
    { code: '3205', designation: 'Organisation internationale' },
    { code: '3210', designation: 'État, collectivité ou établissement public étranger' },
    { code: '3220', designation: 'Société étrangère non immatriculée au RCS' },
    { code: '3290', designation: 'Autre personne morale de droit étranger' },
    { code: '4110', designation: 'Établissement public national à caractère industriel ou commercial doté d\'un comptable public' },
    { code: '4120', designation: 'Établissement public national à caractère industriel ou commercial non doté d\'un comptable public' },
    { code: '4130', designation: 'Exploitant public' },
    { code: '4140', designation: 'Établissement public local à caractère industriel ou commercial' },
    { code: '4150', designation: 'Régie d\'une collectivité locale à caractère industriel ou commercial' },
    { code: '4160', designation: 'Institution Banque de France' },
    { code: '5191', designation: 'Société de caution mutuelle' },
    { code: '5192', designation: 'Société coopérative de banque populaire' },
    { code: '5193', designation: 'Caisse de crédit maritime mutuel' },
    { code: '5194', designation: 'Caisse (fédérale) de crédit mutuel' },
    { code: '5195', designation: 'Association coopérative inscrite (droit local Alsace Moselle)' },
    { code: '5196', designation: 'Caisse d\'épargne et de prévoyance à forme coopérative' },
    { code: '5202', designation: 'Société en nom collectif' },
    { code: '5203', designation: 'Société en nom collectif coopérative' },
    { code: '5306', designation: 'Société en commandite simple' },
    { code: '5307', designation: 'Société en commandite simple coopérative' },
    { code: '5308', designation: 'Société en commandite par actions' },
    { code: '5309', designation: 'Société en commandite par actions coopérative' },
    { code: '5310', designation: 'Société en libre partenariat (SLP)' },
    { code: '5370', designation: 'Société de Participations Financières de Profession Libérale Société en commandite par actions (SPFPL SCA)' },
    { code: '5385', designation: 'Société d\'exercice libéral en commandite par actions' },
    { code: '5410', designation: 'SARL nationale' },
    { code: '5415', designation: 'SARL d\'économie mixte' },
    { code: '5422', designation: 'SARL immobilière pour le commerce et l\'industrie (SICOMI)' },
    { code: '5426', designation: 'SARL immobilière de gestion' },
    { code: '5430', designation: 'SARL d\'aménagement foncier et d\'équipement rural (SAFER)' },
    { code: '5431', designation: 'SARL mixte d\'intérêt agricole (SMIA)' },
    { code: '5432', designation: 'SARL d\'intérêt collectif agricole (SICA)' },
    { code: '5442', designation: 'SARL d\'attribution' },
    { code: '5443', designation: 'SARL coopérative de construction' },
    { code: '5451', designation: 'SARL coopérative de consommation' },
    { code: '5453', designation: 'SARL coopérative artisanale' },
    { code: '5454', designation: 'SARL coopérative d\'intérêt maritime' },
    { code: '5455', designation: 'SARL coopérative de transport' },
    { code: '5458', designation: 'SARL coopérative de production (SCOP)' },
    { code: '5459', designation: 'SARL union de sociétés coopératives' },
    { code: '5460', designation: 'Autre SARL coopérative' },
    { code: '5470', designation: 'Société de Participations Financières de Profession Libérale Société à responsabilité limitée (SPFPL SARL)' },
    { code: '5485', designation: 'Société d\'exercice libéral à responsabilité limitée' },
    { code: '5499', designation: 'Société à responsabilité limitée (sans autre indication)' },
    { code: '5505', designation: 'SA à participation ouvrière à conseil d\'administration' },
    { code: '5510', designation: 'SA nationale à conseil d\'administration' },
    { code: '5515', designation: 'SA d\'économie mixte à conseil d\'administration' },
    { code: '5520', designation: 'Fonds à forme sociétale à conseil d\'administration' },
    { code: '5522', designation: 'SA immobilière pour le commerce et l\'industrie (SICOMI) à conseil d\'administration' },
    { code: '5525', designation: 'SA immobilière d\'investissement à conseil d\'administration' },
    { code: '5530', designation: 'SA d\'aménagement foncier et d\'équipement rural (SAFER) à conseil d\'administration' },
    { code: '5531', designation: 'Société anonyme mixte d\'intérêt agricole (SMIA) à conseil d\'administration' },
    { code: '5532', designation: 'SA d\'intérêt collectif agricole (SICA) à conseil d\'administration' },
    { code: '5542', designation: 'SA d\'attribution à conseil d\'administration' },
    { code: '5543', designation: 'SA coopérative de construction à conseil d\'administration' },
    { code: '5546', designation: 'SA de HLM à conseil d\'administration' },
    { code: '5547', designation: 'SA coopérative de production de HLM à conseil d\'administration' },
    { code: '5548', designation: 'SA de crédit immobilier à conseil d\'administration' },
    { code: '5551', designation: 'SA coopérative de consommation à conseil d\'administration' },
    { code: '5552', designation: 'SA coopérative de commerçants-détaillants à conseil d\'administration' },
    { code: '5553', designation: 'SA coopérative artisanale à conseil d\'administration' },
    { code: '5554', designation: 'SA coopérative (d\'intérêt) maritime à conseil d\'administration' },
    { code: '5555', designation: 'SA coopérative de transport à conseil d\'administration' },
    { code: '5558', designation: 'SA coopérative de production (SCOP) à conseil d\'administration' },
    { code: '5559', designation: 'SA union de sociétés coopératives à conseil d\'administration' },
    { code: '5560', designation: 'Autre SA coopérative à conseil d\'administration' },
    { code: '5570', designation: 'Société de Participations Financières de Profession Libérale Société anonyme à conseil d\'administration (SPFPL SA à conseil d\'administration)' },
    { code: '5585', designation: 'Société d\'exercice libéral à forme anonyme à conseil d\'administration' },
    { code: '5599', designation: 'SA à conseil d\'administration (s.a.i.)' },
    { code: '5605', designation: 'SA à participation ouvrière à directoire' },
    { code: '5610', designation: 'SA nationale à directoire' },
    { code: '5615', designation: 'SA d\'économie mixte à directoire' },
    { code: '5620', designation: 'Fonds à forme sociétale à directoire' },
    { code: '5622', designation: 'SA immobilière pour le commerce et l\'industrie (SICOMI) à directoire' },
    { code: '5625', designation: 'SA immobilière d\'investissement à directoire' },
    { code: '5630', designation: 'Safer anonyme à directoire' },
    { code: '5631', designation: 'SA mixte d\'intérêt agricole (SMIA)' },
    { code: '5632', designation: 'SA d\'intérêt collectif agricole (SICA)' },
    { code: '5642', designation: 'SA d\'attribution à directoire' },
    { code: '5643', designation: 'SA coopérative de construction à directoire' },
    { code: '5646', designation: 'SA de HLM à directoire' },
    { code: '5647', designation: 'Société coopérative de production de HLM anonyme à directoire' },
    { code: '5648', designation: 'SA de crédit immobilier à directoire' },
    { code: '5651', designation: 'SA coopérative de consommation à directoire' },
    { code: '5652', designation: 'SA coopérative de commerçants-détaillants à directoire' },
    { code: '5653', designation: 'SA coopérative artisanale à directoire' },
    { code: '5654', designation: 'SA coopérative d\'intérêt maritime à directoire' },
    { code: '5655', designation: 'SA coopérative de transport à directoire' },
    { code: '5658', designation: 'SA coopérative de production (SCOP) à directoire' },
    { code: '5659', designation: 'SA union de sociétés coopératives à directoire' },
    { code: '5660', designation: 'Autre SA coopérative à directoire' },
    { code: '5670', designation: 'Société de Participations Financières de Profession Libérale Société anonyme à Directoire (SPFPL SA à directoire)' },
    { code: '5685', designation: 'Société d\'exercice libéral à forme anonyme à directoire' },
    { code: '5699', designation: 'SA à directoire (s.a.i.)' },
    { code: '5710', designation: 'SAS, société par actions simplifiée' },
    { code: '5770', designation: 'Société de Participations Financières de Profession Libérale Société par actions simplifiée (SPFPL SAS)' },
    { code: '5785', designation: 'Société d\'exercice libéral par action simplifiée' },
    { code: '5800', designation: 'Société européenne' },
    { code: '6100', designation: 'Caisse d\'Épargne et de Prévoyance' },
    { code: '6210', designation: 'Groupement européen d\'intérêt économique (GEIE)' },
    { code: '6220', designation: 'Groupement d\'intérêt économique (GIE)' },
    { code: '6316', designation: 'Coopérative d\'utilisation de matériel agricole en commun (CUMA)' },
    { code: '6317', designation: 'Société coopérative agricole' },
    { code: '6318', designation: 'Union de sociétés coopératives agricoles' },
    { code: '6411', designation: 'Société d\'assurance à forme mutuelle' },
    { code: '6511', designation: 'Sociétés Interprofessionnelles de Soins Ambulatoires' },
    { code: '6521', designation: 'Société civile de placement collectif immobilier (SCPI)' },
    { code: '6532', designation: 'Société civile d\'intérêt collectif agricole (SICA)' },
    { code: '6533', designation: 'Groupement agricole d\'exploitation en commun (GAEC)' },
    { code: '6534', designation: 'Groupement foncier agricole' },
    { code: '6535', designation: 'Groupement agricole foncier' },
    { code: '6536', designation: 'Groupement forestier' },
    { code: '6537', designation: 'Groupement pastoral' },
    { code: '6538', designation: 'Groupement foncier et rural' },
    { code: '6539', designation: 'Société civile foncière' },
    { code: '6540', designation: 'Société civile immobilière' },
    { code: '6541', designation: 'Société civile immobilière de construction-vente' },
    { code: '6542', designation: 'Société civile d\'attribution' },
    { code: '6543', designation: 'Société civile coopérative de construction' },
    { code: '6544', designation: 'Société civile immobilière d\' accession progressive à la propriété' },
    { code: '6551', designation: 'Société civile coopérative de consommation' },
    { code: '6554', designation: 'Société civile coopérative d\'intérêt maritime' },
    { code: '6558', designation: 'Société civile coopérative entre médecins' },
    { code: '6560', designation: 'Autre société civile coopérative' },
    { code: '6561', designation: 'SCP d\'avocats' },
    { code: '6562', designation: 'SCP d\'avocats aux conseils' },
    { code: '6563', designation: 'SCP d\'avoués d\'appel' },
    { code: '6564', designation: 'SCP d\'huissiers' },
    { code: '6565', designation: 'SCP de notaires' },
    { code: '6566', designation: 'SCP de commissaires-priseurs' },
    { code: '6567', designation: 'SCP de greffiers de tribunal de commerce' },
    { code: '6568', designation: 'SCP de conseils juridiques' },
    { code: '6569', designation: 'SCP de commissaires aux comptes' },
    { code: '6571', designation: 'SCP de médecins' },
    { code: '6572', designation: 'SCP de dentistes' },
    { code: '6573', designation: 'SCP d\'infirmiers' },
    { code: '6574', designation: 'SCP de masseurs-kinésithérapeutes' },
    { code: '6575', designation: 'SCP de directeurs de laboratoire d\'analyse médicale' },
    { code: '6576', designation: 'SCP de vétérinaires' },
    { code: '6577', designation: 'SCP de géomètres experts' },
    { code: '6578', designation: 'SCP d\'architectes' },
    { code: '6585', designation: 'Autre société civile professionnelle' },
    { code: '6589', designation: 'Société civile de moyens' },
    { code: '6595', designation: 'Caisse locale de crédit mutuel' },
    { code: '6596', designation: 'Caisse de crédit agricole mutuel' },
    { code: '6597', designation: 'Société civile d\'exploitation agricole' },
    { code: '6598', designation: 'Exploitation agricole à responsabilité limitée' },
    { code: '6599', designation: 'Autre société civile' },
    { code: '6901', designation: 'Autre personne de droit privé inscrite au registre du commerce et des sociétés' },
    { code: '7111', designation: 'Autorité constitutionnelle' },
    { code: '7112', designation: 'Autorité administrative ou publique indépendante' },
    { code: '7113', designation: 'Ministère' },
    { code: '7120', designation: 'Service central d\'un ministère' },
    { code: '7150', designation: 'Service du ministère de la Défense' },
    { code: '7160', designation: 'Service déconcentré à compétence nationale d\'un ministère (hors Défense)' },
    { code: '7171', designation: 'Service déconcentré de l\'État à compétence (inter) régionale' },
    { code: '7172', designation: 'Service déconcentré de l\'État à compétence (inter) départementale' },
    { code: '7179', designation: '(Autre) Service déconcentré de l\'État à compétence territoriale' },
    { code: '7190', designation: 'Ecole nationale non dotée de la personnalité morale' },
    { code: '7210', designation: 'Commune et commune nouvelle' },
    { code: '7220', designation: 'Département' },
    { code: '7225', designation: 'Collectivité et territoire d\'Outre Mer' },
    { code: '7229', designation: '(Autre) Collectivité territoriale' },
    { code: '7230', designation: 'Région' },
    { code: '7312', designation: 'Commune associée et commune déléguée' },
    { code: '7313', designation: 'Section de commune' },
    { code: '7314', designation: 'Ensemble urbain' },
    { code: '7321', designation: 'Association syndicale autorisée' },
    { code: '7322', designation: 'Association foncière urbaine' },
    { code: '7323', designation: 'Association foncière de remembrement' },
    { code: '7331', designation: 'Établissement public local d\'enseignement' },
    { code: '7340', designation: 'Pôle métropolitain' },
    { code: '7341', designation: 'Secteur de commune' },
    { code: '7342', designation: 'District urbain' },
    { code: '7343', designation: 'Communauté urbaine' },
    { code: '7344', designation: 'Métropole' },
    { code: '7345', designation: 'Syndicat intercommunal à vocation multiple (SIVOM)' },
    { code: '7346', designation: 'Communauté de communes' },
    { code: '7347', designation: 'Communauté de villes' },
    { code: '7348', designation: 'Communauté d\'agglomération' },
    { code: '7349', designation: 'Autre établissement public local de coopération non spécialisé ou entente' },
    { code: '7351', designation: 'Institution interdépartementale ou entente' },
    { code: '7352', designation: 'Institution interrégionale ou entente' },
    { code: '7353', designation: 'Syndicat intercommunal à vocation unique (SIVU)' },
    { code: '7354', designation: 'Syndicat mixte fermé' },
    { code: '7355', designation: 'Syndicat mixte ouvert' },
    { code: '7356', designation: 'Commission syndicale pour la gestion des biens indivis des communes' },
    { code: '7357', designation: 'Pôle d\'équilibre territorial et rural (PETR)' },
    { code: '7361', designation: 'Centre communal d\'action sociale' },
    { code: '7362', designation: 'Caisse des écoles' },
    { code: '7363', designation: 'Caisse de crédit municipal' },
    { code: '7364', designation: 'Établissement d\'hospitalisation' },
    { code: '7365', designation: 'Syndicat inter hospitalier' },
    { code: '7366', designation: 'Établissement public local social et médico-social' },
    { code: '7367', designation: 'Centre Intercommunal d\'action sociale (CIAS)' },
    { code: '7371', designation: 'Office public d\'habitation à loyer modéré (OPHLM)' },
    { code: '7372', designation: 'Service départemental d\'incendie et de secours (SDIS)' },
    { code: '7373', designation: 'Établissement public local culturel' },
    { code: '7378', designation: 'Régie d\'une collectivité locale à caractère administratif' },
    { code: '7379', designation: '(Autre) Établissement public administratif local' },
    { code: '7381', designation: 'Organisme consulaire' },
    { code: '7382', designation: 'Établissement public national ayant fonction d\'administration centrale' },
    { code: '7383', designation: 'Établissement public national à caractère scientifique culturel et professionnel' },
    { code: '7384', designation: 'Autre établissement public national d\'enseignement' },
    { code: '7385', designation: 'Autre établissement public national administratif à compétence territoriale limitée' },
    { code: '7389', designation: 'Établissement public national à caractère administratif' },
    { code: '7410', designation: 'Groupement d\'intérêt public (GIP)' },
    { code: '7430', designation: 'Établissement public des cultes d\'Alsace-Lorraine' },
    { code: '7450', designation: 'Etablissement public administratif, cercle et foyer dans les armées' },
    { code: '7470', designation: 'Groupement de coopération sanitaire à gestion publique' },
    { code: '7490', designation: 'Autre personne morale de droit administratif' },
    { code: '8110', designation: 'Régime général de la Sécurité Sociale' },
    { code: '8120', designation: 'Régime spécial de Sécurité Sociale' },
    { code: '8130', designation: 'Institution de retraite complémentaire' },
    { code: '8140', designation: 'Mutualité sociale agricole' },
    { code: '8150', designation: 'Régime maladie des non-salariés non agricoles' },
    { code: '8160', designation: 'Régime vieillesse ne dépendant pas du régime général de la Sécurité Sociale' },
    { code: '8170', designation: 'Régime d\'assurance chômage' },
    { code: '8190', designation: 'Autre régime de prévoyance sociale' },
    { code: '8210', designation: 'Mutuelle' },
    { code: '8250', designation: 'Assurance mutuelle agricole' },
    { code: '8290', designation: 'Autre organisme mutualiste' },
    { code: '8310', designation: 'Comité social économique d’entreprise' },
    { code: '8311', designation: 'Comité social économique d\'établissement' },
    { code: '8410', designation: 'Syndicat de salariés' },
    { code: '8420', designation: 'Syndicat patronal' },
    { code: '8450', designation: 'Ordre professionnel ou assimilé' },
    { code: '8470', designation: 'Centre technique industriel ou comité professionnel du développement économique' },
    { code: '8490', designation: 'Autre organisme professionnel' },
    { code: '8510', designation: 'Institution de prévoyance' },
    { code: '8520', designation: 'Institution de retraite supplémentaire' },
    { code: '9110', designation: 'Syndicat de copropriété' },
    { code: '9150', designation: 'Association syndicale libre' },
    { code: '9210', designation: 'Association non déclarée' },
    { code: '9220', designation: 'Association déclarée' },
    { code: '9221', designation: 'Association déclarée d\'insertion par l\'économique' },
    { code: '9222', designation: 'Association intermédiaire' },
    { code: '9223', designation: 'Groupement d\'employeurs' },
    { code: '9224', designation: 'Association d\'avocats à responsabilité professionnelle individuelle' },
    { code: '9230', designation: 'Association déclarée, reconnue d\'utilité publique' },
    { code: '9240', designation: 'Congrégation' },
    { code: '9260', designation: 'Association de droit local (Bas-Rhin, Haut-Rhin et Moselle)' },
    { code: '9300', designation: 'Fondation' },
    { code: '9900', designation: 'Autre personne morale de droit privé' },
    { code: '9970', designation: 'Groupement de coopération sanitaire à gestion privée' }
];

