when@dev:
    monolog:
        handlers:
            main:
                type: rotating_file
                path: '%kernel.logs_dir%/app.log'
                max_files: 360
                level: info
                formatter: monolog.formatter.line
                channels: ['!event']
                bubble: false

when@prod:
    monolog:
        handlers:
            main:
                type: rotating_file
                path: '%kernel.logs_dir%/app.log'
                max_files: 360
                level: info
                formatter: monolog.formatter.line
                channels: ['!event']
                bubble: false
