when@dev:
    monolog:
        handlers:
            main:
                type: rotating_file
                path: '%kernel.logs_dir%/app.log'
                max_files: 360
                level: info
                formatter: monolog.formatter.line
                date_format: 'Y-m-d'  # Format de la date utilisé dans le nom de fichier (Année-Mois-Jour)
                channels: [ "!event" ]
            nested:
                type: rotating_file
                path: '%kernel.logs_dir%/app.log'
                level: notice
                formatter: monolog.formatter.line
when@prod:
    monolog:
        handlers:
            main:
                type: rotating_file
                path: '%kernel.logs_dir%/app.log'
                max_files: 360
                level: info
                formatter: monolog.formatter.line
                date_format: 'Y-m-d'  # Format de la date utilisé dans le nom de fichier (Année-Mois-Jour)
                channels: [ "!event" ]
            nested:
                type: rotating_file
                path: '%kernel.logs_dir%/app.log'
                level: notice
                formatter: monolog.formatter.line