nelmio_cors:
    defaults:
        allow_credentials: false           # true seulement si tu utilises des cookies cross-site
        allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With']
        expose_headers: ['Link', 'Location']
        allow_methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS']
        max_age: 3600
        hosts: []                          # vide = toutes les routes cibles
    paths:
        '^/api/': ~                        # n’applique que pour tes endpoints d’API
