security:
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        app_provider:
            entity:
                class: App\Entity\User
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        api:
            pattern: ^/api
            stateless: true
            jwt: ~
            entry_point: jwt
        main:
            context: main
            lazy: true
            provider: app_provider
            form_login:
                login_path: app_user_login
                check_path: app_user_login
            logout:
                path: app_user_logout
                target: home
            user_checker: App\Security\UserConfirmationPatient

    access_control:


