security:
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider

    providers:
        app_provider:
            entity:
                class: App\Entity\User
                property: email
    firewalls:
        admin:
            context: admin
            lazy: true
            pattern: ^/api/login_check$
            stateless: true
            json_login:
                check_path: /api/login_check
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
        api:
            pattern: ^/api
            stateless: true
            jwt: ~
            entry_point: jwt
        main:
            context: main
            lazy: true
            provider: app_provider
            form_login:
                login_path: app_user_login
                check_path: app_user_login
            logout:
                path: app_user_logout
                target: home
            user_checker: App\Security\UserConfirmationPatient


    role_hierarchy:
        ROLE_ADMIN_OSMOSE:
            - ROLE_SUPER_ADMIN
            - ROLE_ADMIN
        ROLE_SUPER_ADMIN:
            - ROLE_ADMIN
        ROLE_ADMIN: []
        ROLE_PATIENT: []


    access_control:
        - { path: ^/api/login_check, roles: PUBLIC_ACCESS }
        - { path: ^/compte, roles: ROLE_PATIENT }
        - { path: ^/centre, roles: ROLE_PATIENT }
        - { path: ^/admin/login, roles: PUBLIC_ACCESS }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/admin, roles: ROLE_SUPER_ADMIN }
        - { path: ^/admin, roles: ROLE_ADMIN_OSMOSE }


